[phases.build]
nixPkgs = [
    "python311",
    "python311Packages.pip"
]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
    "python init_railway_db.py"
]

[start]
cmd = "gunicorn application:app"